alias eb="cd /Users/aatit/Programming/ebpearls"
alias pdp="cd /Users/aatit/Programming/GithubExplore/pdp"
alias fa="cd /Users/aatit/Programming/GithubExplore/flutter"
alias ge="cd /Users/aatit/Programming/GithubExplore"
alias snapdrop="cd /Users/aatit/Programming/GithubExplore/Projects/snapdrop"
